### ISSUE TITLE
Add more UI tests

### ISSUE THREAD

**Issue by mondeja** [ericcornelissen/tmp#223]
- [ ] Language options appears in language selector on click (#242)
- [ ] All languages are included in the language selector except the language of the page
- [ ] Change language using language selector
- [ ] Localized pages are translated
- [ ] Localized titles of icons from `aliases.loc` data property (#225)
- [ ] Advice about icons remove in next major versions (#233)
- [ ] More complete tests for compact layout (#154)
- [ ] Refactor details view using same buttons as cards and add tests (#154)
